services:
  - type: web
    name: resume-maker-backend
    dockerfilePath: backend/Dockerfile
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    rootDir: backend
    ports:
      - 8000
    envVars:
      - key: DATABASE_URL
        sync: false # Set this value in the Render dashboard

  - type: web
    name: resume-maker-frontend
    dockerfilePath: frontend/Dockerfile
    startCommand: "streamlit run app.py --server.port 8501 --server.address 0.0.0.0"
    rootDir: frontend
    ports:
      - 8501
    envVars:
      - key: BACKEND_URL
        value: http://resume-maker-backend:8000 # Internal Render service discovery
